######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 18 21:58:46 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/hardy/radcode/trunk/qt/ex1/. .

# Input
SOURCES += ex1.cpp
