######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 21 10:52:07 2009
######################################################################

QT += webkit
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/hardy/radcode/trunk/qt/browser/. .

# Input
HEADERS += browser.h
FORMS += browser.ui
SOURCES += browser.cpp main.cpp
