#! /bin/sh
### BEGIN INIT INFO
# Provides:          testservice
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: just a test service
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions


case "$1" in
    start)
        start-stop-daemon --start --background --exec /etc/init.d/testservice -- background
        ;;
    background)
        while [ 1 ];do
           sleep 5
           echo `date` >> /tmp/log
        done
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

