
def set_options(opts):
    opts.tool_options('compiler_cxx')

def configure(conf):
    conf.check_tool('compiler_cxx')
    conf.check_tool('node_addon')

def build(bld):
    obj = bld.new_task_gen('cxx', 'shlib', 'node_addon')
    obj.cxxflags = ["-g", "-Wall"]
    obj.target = "helloworld"
    obj.source = "helloworld.cc"


