######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 22 09:47:38 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/mbains/workspace/radcode/qt/converter/. .

# Input
HEADERS += byteconverterdialog.h
SOURCES += byteconverterdialog.cpp converter.cpp
