// Generated by IcedCoffeeScript 1.3.3d
(function() {
  var func, getter, iced, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  func = function(x, cb) {
    return setTimeout((function() {
      console.log("done " + x);
      return cb(5);
    }), 1000);
  };

  getter = function(cb) {
    var answer, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "asyncwait.coffee",
        funcname: "getter"
      });
      func(10, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return answer = arguments[0];
          };
        })(),
        lineno: 36
      }));
      __iced_deferrals._fulfill();
    })(function() {
      console.log("in async func " + answer);
      return cb(answer);
    });
  };

  getter(function(mine) {
    return console.log("through async " + mine);
  });

}).call(this);
