// Generated by IcedCoffeeScript 1.3.3d
(function() {
  var iced, sleep, test1, test2, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  sleep = (function(t, cb) {
    return setTimeout((function() {
      return cb();
    }), t);
  });

  test1 = function() {
    var dummy, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    console.log("1 going to sleep");
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "sleep.coffee",
        funcname: "test1"
      });
      sleep(5000, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return dummy = arguments[0];
          };
        })(),
        lineno: 11
      }));
      __iced_deferrals._fulfill();
    })(function() {
      return console.log("1 done sleeping");
    });
  };

  test2 = function() {
    var dummy, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    console.log("2 going to sleep");
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "sleep.coffee",
        funcname: "test2"
      });
      sleep(3000, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return dummy = arguments[0];
          };
        })(),
        lineno: 16
      }));
      __iced_deferrals._fulfill();
    })(function() {
      return console.log("2 done sleeping");
    });
  };

  test1();

  test2();

}).call(this);
