// Generated by IcedCoffeeScript 1.3.3d
(function() {
  var y;

  y = 20;

  while (y -= 1) {
    (function(x) {
      return setTimeout((function() {
        return console.log("async timeout " + x);
      }), y * 50);
    })(y);
  }

}).call(this);
