######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 21 12:12:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/hardy/radcode/trunk/qt/slider/. .

# Input
SOURCES += slider.cpp
