######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 19 16:49:48 2009
######################################################################

TEMPLATE = app
CONFIG += qt debug
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/mbains/workspace/radcode/qt/borderlayout/. .

# Input
HEADERS += borderlayout.h window.h
SOURCES += borderlayout.cpp main.cpp window.cpp
