######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 21 10:52:07 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/hardy/radcode/trunk/qt/dialog/. .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
