/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class exampleJNI {
  public final static native long new_klass();
  public final static native void delete_klass(long jarg1);
  public final static native int klass_arraySum(long jarg1, klass jarg1_, long jarg2);
  public final static native int klass_add(long jarg1, klass jarg1_, int jarg2, int jarg3);
  public final static native long klass_trace(long jarg1, klass jarg1_, long jarg2);
  public final static native long new_klassArray(int jarg1);
  public final static native void delete_klassArray(long jarg1);
  public final static native long klassArray_getitem(long jarg1, int jarg2);
  public final static native void klassArray_setitem(long jarg1, int jarg2, long jarg3, klass jarg3_);
  public final static native void createKlasses(long jarg1, int jarg2);
}
