/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static SWIGTYPE_p_p_klass new_klassArray(int nelements) {
    long cPtr = exampleJNI.new_klassArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_klass(cPtr, false);
  }

  public static void delete_klassArray(SWIGTYPE_p_p_klass ary) {
    exampleJNI.delete_klassArray(SWIGTYPE_p_p_klass.getCPtr(ary));
  }

  public static klass klassArray_getitem(SWIGTYPE_p_p_klass ary, int index) {
    long cPtr = exampleJNI.klassArray_getitem(SWIGTYPE_p_p_klass.getCPtr(ary), index);
    return (cPtr == 0) ? null : new klass(cPtr, false);
  }

  public static void klassArray_setitem(SWIGTYPE_p_p_klass ary, int index, klass value) {
    exampleJNI.klassArray_setitem(SWIGTYPE_p_p_klass.getCPtr(ary), index, klass.getCPtr(value), value);
  }

  public static void createKlasses(SWIGTYPE_p_p_klass klassArray, int size) {
    exampleJNI.createKlasses(SWIGTYPE_p_p_klass.getCPtr(klassArray), size);
  }

}
