/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class klass {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected klass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(klass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_klass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public klass() {
    this(exampleJNI.new_klass(), true);
  }

  public int arraySum(SWIGTYPE_p_double array) {
    return exampleJNI.klass_arraySum(swigCPtr, this, SWIGTYPE_p_double.getCPtr(array));
  }

  public int add(int x, int y) {
    return exampleJNI.klass_add(swigCPtr, this, x, y);
  }

  public SWIGTYPE_p_PyArrayObject trace(SWIGTYPE_p_PyObject args) {
    long cPtr = exampleJNI.klass_trace(swigCPtr, this, SWIGTYPE_p_PyObject.getCPtr(args));
    return (cPtr == 0) ? null : new SWIGTYPE_p_PyArrayObject(cPtr, false);
  }

}
