######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 21 10:52:07 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/hardy/radcode/trunk/qt/calculatorform/. .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
